baseURL: 'https://ilyaas.netlify.app/'
languageCode: en-us
title: Ilyaas Kapadia
theme: ["PaperMod","hugo-video"]
paginate: 100
enableRobotsTXT: true
menu:
  main:
    - name: Tags
      identifier: tags
      url: /tags/
      weight: 10
    - name: Search
      identifier: search
      url: /search/
      weight: 10
    - name: Reading List
      identifier: read
      url: /read/
      weight: 10
    - name: Subscribe
      identifier: subscribe
      url: /subscribe/
      weight: 10



params:
  env: production
  style: auto
  copyCodeButton: true
  dateFormat: 2 January 2006
  paginationSinglePost: true

params:
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowWordCount: true
    #  ShowFullTextinRSS: true
  homeInfoParams:
      Title: Guten Tag
      Content: A man in the mountains pursuing his dream.
          Documenting my life, my journey.

  socialIcons: # optional
      - name: "youtube"
        url: "https://youtube.com/c/IlyaasKapadia"
      - name: "instagram"
        url: "https://instagram.com/ilyaas.kapadia"
      - name: "other"
        url: "https://mumbaimirror.indiatimes.com/others/leisure/hot-wheels/articleshow/70625800.cms"
      - name: "goodreads"
        url: "https://www.goodreads.com/user/show/155615846-ilyaas-kapadia"
      - name: "rss"
        url: "https://ilyaas.netlify.app/index.xml"






  ShowWordCount: true #show word count

#params:
#  instagram:
#    appID: ""
#    clientToken: ""

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

  ShowFullTextinRSS: true
