baseURL = 'https://ilyaas.netlify.app/'
languageCode = 'en-us'
title = 'Blog | Ilyaas Kapadia'
theme = 'PaperMod'
paginate = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/post/"
weight = 10

[[menu.main]]
name = "Tags"
identifier = "tags"
url = "/tags/"
weight = 10


[[menu.main]]
name = "Search"
identifier = "search"
url = "/search/"
weight = 10

[params]
author = "Ilyaas Kapadia"
description = "Mountain man pursuing my dream and documenting the journey"
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
dateFormat = "2 January 2006"
paginationSinglePost = true
rssAsSocialIcon = true

[[menu.main]]
name = "Youtube"
id = "youtube"
url = "https://www.youtube.com/c/IlyaasKapadia"
